services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bemo-backend
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - bemo-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:8080
    container_name: bemo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bemo-net

networks:
  bemo-net:
    driver: bridge